### ISSUE TITLE
Incorporate Sonde DA into JEDI for RRFS

### ISSUE THREAD

**Issue by delippi** [NOAA-EMC/RDASApp#232]
## Description
The UFO in JEDI is the component that not only computes model-simulated observations, but also houses filters and methods for observation QC, ob errors, and bias correction. The GSI observer is the equivalent. Many forward operators for various observations have been developed for the UFO. These operators can be utilized in RDAS. However these operators still must be tested for RDAS. The steps for transition by observation platform are as follows:

1. Establish IODA processing
2. Establish operator in UFO
3. Establish YAML input file
4. Validate with test assimilation experiments
5. Create ctest, if necessary

Sonde data is bufr obtype=*20

## Requirements
To create yaml configurations for assimilating sonde data.

## Acceptance Criteria (Definition of Done)

- [x] Phase 1 validation (hofx validation using GSI-IODA and GSI-geovals as necessary; GSI vs FV3-JEDI)
- [x] Phase 2 validation (QC validation; no reliance on GSI except to be used as the baseline; GSI vs FV3-JEDI)
- [ ] Phase 3 validation (FV3-JEDI and GSI vs MPAS-JEDI)

- Link any relevant pull requests here:
  - #245 
  - PR for Phase 3 (to be added later)

## Dependencies
- #188 is useful to be used as a building block for this work.
- This is one of the more important ob types to start cycling MPAS-JEDI so we need this ready ASAP.

**Comment by delippi** [comment]
**Phase 2 update**
I did Phase 1 validation awhile ago for these types (unofficially; not documented). They use the exact same operator as mesonet, so I feel confident about it. I will likely still do Phase 1 again just to have it documented.

Here are some preliminary results with some sonde yamls mostly based on the mesonet yamls in PR #188. Ob counts are definitely incorrect. Even when removing all QC the ob counts are badt (for example, only 96 airTemp obs used with/without any QC). This has been noticed before; need to investigate. Increments look very different as well; probably due to mismatch in ob errors? Omb look pretty good (which should mean hofx in Phase 1 is fine).

airTemperature
![fv3jedi_vs_gsi_increment_airTemperature_adpupa_airTemperature_120](https://github.com/user-attachments/assets/5b6e971a-b482-479c-bcd2-7a2141f22fef)
![hist_adpupa_airTemperature_120](https://github.com/user-attachments/assets/fa441483-fc2d-408f-bfd7-c36e644d9c11)

specificHumidity
![fv3jedi_vs_gsi_increment_airTemperature_adpupa_specificHumidity_120](https://github.com/user-attachments/assets/14fbf187-e698-447d-8cad-56c53aa398b3)
![hist_adpupa_specificHumidity_120](https://github.com/user-attachments/assets/9d7de3e1-a489-4d47-94d6-488763e441e5)

winds
![fv3jedi_vs_gsi_increment_airTemperature_adpupa_winds_220](https://github.com/user-attachments/assets/89d2e857-211b-472b-93ad-83b819c224b2)
![hist_adpupa_winds_220](https://github.com/user-attachments/assets/adc28307-96a2-433b-91ed-4c9f8432263a)

**Comment by delippi** [comment]
**Phase 2 update**
The discrepancy in observation counts between JEDI and GSI for sounding observations was due to two factors:

1. GSI was using `ext_sonde` which isn't something we ought to be using. This namelist option interpolates the observations such that there is at least one pseudo ob per model level.
2. The time window of assimilation is different. GSI uses `time_window_max=1.5`, `nhr_assimilation=3`, and `nhr_obsbin=3` where JEDI seems to only have a time window of 1 hour. For some reason I had to change the GSI `time_window_max=0.99` since setting it to `1.0` still did not work. We need to figure out how to extend the window for JEDI to match the 1.5 window for obs. If I recall correctly, this is important to get higher latency obs that might not be otherwise available at the expense of assimilating some obs more than once.

Now observation counts match exactly (or within 4 for winds) which is the expected result for just a handful of sounding data. 

The current issue is the observation errors do not match close enough. In fact, I've checked that they do not get inflated at all in JEDI (I checked this by prescribing a constant ob error in JEDI and there was no change). From phase 1 testing, I seem to recall that the `ObsErrorFactorPressureCheck` really only made a difference for surface obs. I've already tried `ObsErrorFactorConventional`, but I haven't been successful getting any movement in the errors with that (I had to test it with the offline domain check; it seems this function also doesn't correctly use the qcflags from the online domain check). I need to dig into the GSI code to find out what it is doing with these obs. Then I can more easily determine what I need to do in JEDI.

airTemperature
![fv3jedi_vs_gsi_increment_airTemperature_adpupa_airTemperature_120](https://github.com/user-attachments/assets/9c376756-6d32-4345-b6d6-22a7ee48e8cc)
![hist_adpupa_airTemperature_120](https://github.com/user-attachments/assets/0111accf-07af-4f15-b53d-33727c4b543d)

specificHumidity
![fv3jedi_vs_gsi_increment_airTemperature_adpupa_specificHumidity_120](https://github.com/user-attachments/assets/25f3552e-5007-411f-a50a-22bbe73c3d86)
![hist_adpupa_specificHumidity_120](https://github.com/user-attachments/assets/0aa095c6-d0c9-4544-8d21-5cd6f154b32a)

winds
![fv3jedi_vs_gsi_increment_airTemperature_adpupa_winds_220](https://github.com/user-attachments/assets/242ffce3-4518-4e9b-8c2d-50a14e7f404a)
![hist_adpupa_winds_220](https://github.com/user-attachments/assets/491bb579-4258-41b5-a23f-bde7db2398db)

**Comment by SamuelDegelia-NOAA** [comment]
@delippi Glad we are understanding the time window better! Do you mean that we should disable `ext_sonde` for our GSI runs? I am setting up the GSI run directory for the updated FV3-LAM case and can make this change if needed. 

Also, regarding the obserrs, I recall that GSI has a routine that inflates the obserrs for profiles such as sondes based on their density. I just checked and that inflation occurs in the `errormod` function in `qcmod.f90`. Not sure if that is the difference here but it could be worth checking.

**Comment by delippi** [comment]
> @delippi Glad we are understanding the time window better! Do you mean that we should disable `ext_sonde` for our GSI runs? I am setting up the GSI run directory for the updated FV3-LAM case and can make this change if needed.
> 
> Also, regarding the obserrs, I recall that GSI has a routine that inflates the obserrs for profiles such as sondes based on their density. I just checked and that inflation occurs in the `errormod` function in `qcmod.f90`. Not sure if that is the difference here but it could be worth checking.

Our messages crossed paths. Yes I think we need to disable `ext_sonde` for anything RRFSv2. Shun said it is probably too late for v1.

**Comment by delippi** [comment]
> Also, regarding the obserrs, I recall that GSI has a routine that inflates the obserrs for profiles such as sondes based on their density. I just checked and that inflation occurs in the errormod function in qcmod.f90. Not sure if that is the difference here but it could be worth checking.

@SamuelDegelia-NOAA, thanks for sharing this info. I've confirmed that errormod in qcmod.f90 is being used to inflate my obs in the GSI case. The `ObsErrorFactorConventional` routine was designed to mimic the GSI observer code (i.e., subroutine errormod in qcmod.f90). So I need to keep trying to use that function and see if I can get any movement in the ob errors.

**Comment by delippi** [comment]
I'm able to get `ObsErrorFactorConventional` work now. You must use `obsgrouping` as follows:
```yaml
         obsdatain:
           engine:
             type: H5File
             obsfile: "@OBSFILE@"
           obsgrouping:
             group variables: ["stationIdentification", "dateTime"]
             sort variable: "pressure"
             sort order: "descending"
```

An example of `ObsErrorFactorConventional` is
```yaml
         # Error inflation based on errormod (qcmod.f90)
         - filter: Perform Action
           filter variables:
           - name: windEastward
           where:
           - variable: ObsType/windEastward
             is_in: 220
           action:
             name: inflate error
             inflation variable:
               name: ObsFunction/ObsErrorFactorConventional
               options:
                 inflate variables: [windEastward]
                 pressure: MetaData/pressure
```
The ob errors look so much better, but I'm not sure why my offline domain check has more observations... I need to create an issue to add qcflag checks in the `ObsErrorFactorConventional` much like I recently did for `ObsErrorFactorPressureCheck` so we can just use the online domain check.
![hist_adpupa_winds_220](https://github.com/user-attachments/assets/7f12afab-dc27-47b5-9366-c24bfa224b58)

**Comment by delippi** [comment]
**Phase 2 update**
The difference in observation counts in the previous update was due to user error having modified the ioda data for debugging and forgot to revert--all time information was set to be the analysis time so all observations were accept.

There was also another user error in the configuration used in the previous configuration settings. This is the correct usage (there should **NOT** be `"dateTime"` in the `obsgrouping.group variables`):
```yaml
         obsdatain:
           engine:
             type: H5File
             obsfile: "@OBSFILE@"
           obsgrouping:
             group variables: ["stationIdentification"]
             sort variable: "pressure"
             sort order: "descending"
```
Here are the phase2 results. Note this in a 19Z cycle so the impact is small. I'm including the analysis increments anyway since they show min/max increment values. These results are also using the <ins>online domain check obs</ins>. I think we're ready to submit a PR for phase2 sonde data:

airTemperature
![hist_adpupa_airTemperature_120](https://github.com/user-attachments/assets/44fe366d-12cf-4a74-acd1-9a232d2259d2)
![fv3jedi_vs_gsi_increment_airTemperature_adpupa_airTemperature_120](https://github.com/user-attachments/assets/714d8940-51ef-4aee-921b-c80f4ff4f107)

specificHumidity
![hist_adpupa_specificHumidity_120](https://github.com/user-attachments/assets/97cc9305-8e96-4af9-896f-b06610ff0654)
![fv3jedi_vs_gsi_increment_airTemperature_adpupa_specificHumidity_120](https://github.com/user-attachments/assets/6bc615be-192e-4797-9f79-21f1ebab2528)

winds
![hist_adpupa_winds_220](https://github.com/user-attachments/assets/5cc08857-860a-4688-974c-2fc5844c7ad0)
![fv3jedi_vs_gsi_increment_airTemperature_adpupa_winds_220](https://github.com/user-attachments/assets/f55c93b8-f702-4b3a-be23-6e76cd61fd52)

**Comment by JingCheng-NOAA** [comment]
In my case, for airTemperature/specificHumidity data, the observation number looks similar to GSI after applying all the QC filters, however, the output QCflag doesn't show anything related to out of domain obs, which is strange because in wind data it shows the number out of domain.

**Comment by delippi** [comment]
**Phase 3 update**

Now seemed like a good time to start phase 3 since I wanted to start digging into some errors I was seeing before in MPAS-JEDI and just make sure they are ready for cycling. 

1. MPAS-JEDI isn't currently able to get `saturation_water_vapor_mixing_ratio_wrt_moist_air` in by using `request_saturation_specific_humidity_geovals: true` in `ObsFunction/ObsErrorFactorPressureCheck`. A temporary solution is to just comment out that entire filter in the specificHumidity yamls. ObErrors just won't be inflated correctly. Hence the ob errors for specific humidity in all MPAS cases (for now) will look uninflated.
2. Obs counts for specificHumidity are strangely low in this case; they were exact in the old 19Z FV3-JEDI case. I found this can be fixed by removing the initial `Reject all obs with QualityMarker > 3`. I need to double check what we should be doing. I have a feeling the QM isn't as robust as I'm thinking and we could be more lenient. (see bonus figure at the end). The more relaxed QM handling also doesn't seem to change the final increment results. Not sure if it would be better to keep it more stringent to reduce number of obs since there isn't as much of an impact?
3. ObErrors for winds don't seem to follow GSI as expected.
4. Increments, for the most part, look similar spatially but GSI is more smooth. That shouldn't be related to the use of observations.

airTemperature
![hist_adpupa_airTemperature_120](https://github.com/user-attachments/assets/e8d11b52-722f-4cba-95cd-e22357742f2b)
![fv3jedi_vs_gsi_vs_mpas_increment_airTemperature_adpupa_airTemperature_120](https://github.com/user-attachments/assets/57512934-a133-485b-9a84-2ce27f537e1c)

specificHumidity
![hist_adpupa_specificHumidity_120](https://github.com/user-attachments/assets/548c2b08-58d9-4214-8190-dc2bd50f8e69)
![fv3jedi_vs_gsi_vs_mpas_increment_airTemperature_adpupa_specificHumidity_120](https://github.com/user-attachments/assets/1646bdb1-a9cb-4b93-a952-cdfaeb8329c5)

winds
![hist_adpupa_winds_220](https://github.com/user-attachments/assets/73e3330b-0fe9-4f14-bc02-6cae5f68130f)
![fv3jedi_vs_gsi_vs_mpas_increment_airTemperature_adpupa_winds_220](https://github.com/user-attachments/assets/9950c5c7-382d-4f99-93a7-6e13ae8dadf2)


Bonus figures: specificHumidity without `Reject all obs with QualityMarker > 3`
![hist_adpupa_specificHumidity_120_noRejectList](https://github.com/user-attachments/assets/67a7a854-39cf-48ae-9bde-4ccc089d89e1)
![fv3jedi_vs_gsi_vs_mpas_increment_airTemperature_adpupa_specificHumidity_120_noRejectList](https://github.com/user-attachments/assets/b728f592-7990-4813-9171-a69991a238da)

**Comment by delippi** [comment]
**Another Phase 3 update**
This also includes some tuning associated with Phase 2-type updates. I updated all my testing to the new case which more accurately reflects the RRFSv1 configurations in errtable, convinfo, gsiparm.anl, etc which also needs to be reflected in the JEDI yamls. With Phase 3, we introduce MPAS-JEDI testing; although FV3-JEDI and MPAS-JEDI tend to be fairly similar. The most important thing to compare are the omb and oberrors. Differences in increments can be affected by other parts of the assimilation, of course. There were a few differences in omb and oberrors that I haven't accounted for, but might be okay:

1. **specificHumidity**: ob counts for JEDI are about half of that of GSI.
2. **winds**: ob errors for JEDI are much more flat compared to GSI.

From a use of observation validation perspective, I think sonde looks really good now. I'm not sure if additional tuning would provide much benefit over GSI at this point.

![adpupa_specificHumidity_120](https://github.com/user-attachments/assets/79431ae4-90b0-40fd-ace9-00c7edfa343d)
![adpupa_winds_220](https://github.com/user-attachments/assets/1038394d-cfb2-469a-9218-cd08e7093116)
![adpupa_airTemperature_120](https://github.com/user-attachments/assets/93c35ad7-1be6-4862-ba5a-8b2b14a89679)

**Comment by delippi** [comment]
**Another Phase 3 update**
Turned off SDL/VDL in GSI for comparisons. Updated gross error settings to match RRFSv1. Fixed a bug with double inflating windEastward.

![adpupa_airTemperature_120](https://github.com/user-attachments/assets/11a281f7-8ba9-4f6a-b3a7-69bb52c320b8)
![adpupa_specificHumidity_120](https://github.com/user-attachments/assets/7339b3d5-c202-42a5-ac7f-9951bd1feb1e)
![adpupa_winds_220](https://github.com/user-attachments/assets/14dd5012-fa48-410e-b855-d5f11bc049cc)

**Comment by delippi** [comment]
**Phase 1 (for surface pressure) update**
Finished some phase 1 testing for sonde surface pressure. I previously didn't test this type since there was some trouble getting these obs in bufr2ioda, but that isn't a problem for phase 1 testing since we use GSI-IODA. I think we can generate these from bufr2ioda with python converter, but I haven't tried yet. Furthermore, I can't use GSI-geovals for any surface pressure tests since I never added that capability to the SfcPCorrected operator, therefore, these tests only used GSI-IODA and were based off previous surface pressure yamls and the result differences are within the expected range.

![Image](https://github.com/user-attachments/assets/8fc4b3dd-db8c-43dd-9d94-acaf7ad8578b)
![Image](https://github.com/user-attachments/assets/ce921e39-876c-40f9-9209-bd894524921e)

**Comment by delippi** [comment]
There doesn't appear to be any 132/232 data (for this case) to test the jedi.yamls. They should mostly follow the 120/220 yamls. I've updated the *32 yamls with the associated observation error and gross error parameters used in GSI. I have no results to show. We may be able to test this again during DA cycling or another case.

**Comment by delippi** [comment]
**Phase 2/3 update**
Redo all phase 3 testing with an updated RDASApp that can assimilate specificHumidity in MPAS-JEDI. All results will be in the following [slide deck](https://docs.google.com/presentation/d/1lcJMdWRKIbF_CSfjh4G7PtJY8L_bxenCyJhJt2dGL9w/edit?usp=sharing).

**Comment by delippi** [comment]
**Update on use of sounding surface pressure in Phase 2**

- I grabbed the python bufr2ioda converter from GDASApp and figured out how to run it. The IODA file was missing MetaData/timeOffset so I quickly added that to the python converter.
- I ran JEDI using the obs and everything seems mostly fine. The analysis increments were quite different, but that isn't unexpected.

![Image](https://github.com/user-attachments/assets/2c09ed87-4db6-4f1e-8669-7127222c8cd8)

**Comment by delippi** [comment]
Just tested ioda obs from both the yaml- and python-based converters in the ctest case; both versions gave identical results as expected. Therefore, it should be safe to replace the yaml-based converter in rrfs-workflow with the python-based converter which will then allow for the use of sounding surfacePressure obs to be assimilated in addition to the other sounding observations (t, q, uv).
